"""Install and remove compress's shell integration without touching Codex config."""

from __future__ import annotations

from dataclasses import dataclass
import hashlib
import json
import os
from pathlib import Path
import re
import shlex
import shutil
import stat
import tempfile
import tomllib


from .service import API_ENDPOINT


START_MARKER = "# >>> compress >>>"
END_MARKER = "# <<< compress <<<"
MANIFEST_VERSION = 1



class InstallError(RuntimeError):
    """Raised when installation cannot proceed without overwriting user-owned state."""


@dataclass(frozen=True)
class InstallResult:
    shell: str
    rc_path: Path | None
    shell_path: Path | None
    config_path: Path
    changed: bool


@dataclass(frozen=True)
class UninstallResult:
    rc_paths: tuple[Path, ...]
    purged: bool


def _home(home: Path | None = None) -> Path:
    return (home or Path.home()).expanduser().resolve()


def config_dir(home: Path | None = None) -> Path:
    if home is None and os.environ.get("XDG_CONFIG_HOME"):
        return Path(os.environ["XDG_CONFIG_HOME"]).expanduser().resolve() / "compress"
    return _home(home) / ".config" / "compress"


def state_dir(home: Path | None = None) -> Path:
    if home is None and os.environ.get("XDG_STATE_HOME"):
        return Path(os.environ["XDG_STATE_HOME"]).expanduser().resolve() / "compress"
    return _home(home) / ".local" / "state" / "compress"


def _atomic_write(path: Path, content: str, mode: int | None = None) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    descriptor, temporary_name = tempfile.mkstemp(prefix=f".{path.name}.", dir=path.parent)
    temporary = Path(temporary_name)
    try:
        with os.fdopen(descriptor, "w", encoding="utf-8") as handle:
            handle.write(content)
        if mode is None and path.exists():
            mode = stat.S_IMODE(path.stat().st_mode)
        os.chmod(temporary, mode if mode is not None else 0o644)
        os.replace(temporary, path)
    except BaseException:
        temporary.unlink(missing_ok=True)
        raise


def _shell_name(shell: str) -> str:
    if shell != "auto":
        selected = Path(shell).name
    else:
        selected = Path(os.environ.get("SHELL", "")).name
        if selected not in {"zsh", "bash"}:
            selected = "zsh" if os.uname().sysname == "Darwin" else "bash"
    if selected not in {"zsh", "bash"}:
        raise InstallError(f"unsupported shell {selected!r}; compress supports zsh and bash")
    return selected


def _rc_path(shell: str, home: Path) -> Path:
    return home / (".zshrc" if shell == "zsh" else ".bashrc")


def _managed_block(shell_path: Path, home: Path) -> str:
    try:
        relative = shell_path.relative_to(home)
        source_path = f'"$HOME/{relative}"'
    except ValueError:
        source_path = shlex.quote(str(shell_path))
    return (
        f"{START_MARKER}\n"
        f"source {source_path}\n"
        f"{END_MARKER}\n"
    )


def _block_pattern() -> re.Pattern[str]:
    return re.compile(
        rf"(?m)^{re.escape(START_MARKER)}\n.*?^{re.escape(END_MARKER)}(?:\n|$)",
        re.DOTALL,
    )


def _has_codex_conflict(content: str) -> bool:
    without_managed = _block_pattern().sub("", content)
    patterns = (
        r"(?m)^\s*(?:function\s+)?codex\s*\(\s*\)\s*\{",
        r"(?m)^\s*alias\s+codex=",
        r"(?m)^\s*(?:source|\.)\s+.*codex-[^\s]*\.sh(?:\s|$)",
    )
    return any(re.search(pattern, without_managed) for pattern in patterns)


def _shell_fragment(
    config_path: Path,
    bin_dir: Path | None = None,
) -> str:
    quoted_config = shlex.quote(str(config_path))
    path_setup = ""
    if bin_dir is not None:
        quoted_bin = shlex.quote(str(bin_dir))
        path_setup = f'''case ":$PATH:" in
    *:{quoted_bin}:*) ;;
    *) export PATH={quoted_bin}:"$PATH" ;;
esac

'''
    codex_function = f'''codex() {{
    local compress_uncompressed=0
    local -a compress_args=()
    local compress_arg

    for compress_arg in "$@"; do
        case "$compress_arg" in
            --uncompressed|--no-compress) compress_uncompressed=1 ;;
            *) compress_args+=("$compress_arg") ;;
        esac
    done

    if [ "$compress_uncompressed" -eq 1 ]; then
        command codex -c features.hooks=false "${{compress_args[@]}}"
        return $?
    fi

    COMPRESS_CODEX_CONFIG={quoted_config} command compress _codex "${{compress_args[@]}}"
}}
'''
    return "# Generated by compress. Edit your compress config, not this file.\n" + path_setup + codex_function


def _default_config(endpoint: str, credential_path: Path, log_path: Path) -> str:
    return f'''[compressor]
endpoint = {json.dumps(endpoint.rstrip("/"))}
model = "cmprs"
api_key_file = {json.dumps(str(credential_path))}
timeout_seconds = 120
retry_503_seconds = 115
min_output_tokens = 512
max_goal_chars = 4000
temperature = 0.6
top_p = 0.95
top_k = 20
min_p = 0.0
presence_penalty = 0.0
repetition_penalty = 1.0

[logging]
path = {json.dumps(str(log_path))}
'''


def install(
    shell: str = "auto",
    endpoint: str | None = None,
    api_key: str | None = None,
    home: Path | None = None,
    *,
    force: bool = False,
    bin_dir: Path | None = None,
) -> InstallResult:
    """Install configuration and the Codex shell integration."""
    user_home = _home(home)
    location_home = user_home if home is not None else None
    selected_shell = _shell_name(shell)
    rc_path = _rc_path(selected_shell, user_home)
    root = config_dir(location_home)
    shell_path = root / "shell.sh"
    config_path = root / "config.toml"
    credential_path = root / "credentials"
    manifest_path = root / "install.json"
    existing_rc = rc_path.read_text(encoding="utf-8") if rc_path.exists() else ""
    existing_fragment = shell_path.read_text(encoding="utf-8") if shell_path.exists() else ""
    if api_key is not None and not api_key.strip():
        raise InstallError("API key must not be blank")
    if _has_codex_conflict(existing_rc) and not force:
        raise InstallError(
            f"{rc_path} already defines or sources a codex wrapper; "
            "remove it or rerun with --force"
        )
    if endpoint is not None and config_path.exists():
        try:
            with config_path.open("rb") as handle:
                configured = tomllib.load(handle).get("compressor", {}).get("endpoint")
        except (OSError, tomllib.TOMLDecodeError, AttributeError) as error:
            raise InstallError(f"cannot read existing {config_path}: {error}") from error
        if configured != endpoint.rstrip("/"):
            raise InstallError(
                f"{config_path} already selects {configured!r}; edit it explicitly "
                "instead of replacing it during installation"
            )

    selected_endpoint = (endpoint if endpoint is not None else API_ENDPOINT).strip().rstrip("/")
    if not config_path.exists() and not selected_endpoint:
        raise InstallError(
            "compression endpoint is not configured; set COMPRESS_ENDPOINT "
            "or pass --endpoint before installing"
        )

    fragment = _shell_fragment(
        config_path,
        bin_dir.expanduser().resolve() if bin_dir is not None else None,
    )
    block = _managed_block(shell_path, user_home)
    pattern = _block_pattern()
    if pattern.search(existing_rc):
        updated_rc = pattern.sub(block, existing_rc, count=1)
    else:
        separator = "" if not existing_rc or existing_rc.endswith("\n") else "\n"
        updated_rc = existing_rc + separator + block

    root.mkdir(parents=True, exist_ok=True, mode=0o700)
    os.chmod(root, 0o700)
    changed = updated_rc != existing_rc or fragment != existing_fragment or not config_path.exists()
    if rc_path.exists() and updated_rc != existing_rc:
        backup = root / f"{rc_path.name}.pre-compress.bak"
        if not backup.exists():
            _atomic_write(backup, existing_rc, stat.S_IMODE(rc_path.stat().st_mode))
    if fragment != existing_fragment:
        _atomic_write(shell_path, fragment)

    if api_key is not None:
        _atomic_write(credential_path, api_key.strip() + "\n", 0o600)
    elif not credential_path.exists():
        _atomic_write(credential_path, "", 0o600)

    if not config_path.exists():
        _atomic_write(
            config_path,
            _default_config(
                selected_endpoint,
                credential_path,
                state_dir(location_home) / "events.jsonl",
            ),
            0o600,
        )
    manifest = {
        "schema_version": MANIFEST_VERSION,
        "shell": selected_shell,
        "rc_path": str(rc_path),
        "shell_path": str(shell_path),
        "config_path": str(config_path),
        "block_sha256": hashlib.sha256(block.encode()).hexdigest(),
    }
    _atomic_write(manifest_path, json.dumps(manifest, indent=2, sort_keys=True) + "\n", 0o600)
    # Activate the integration last, after every sourced/configured file exists.
    if updated_rc != existing_rc:
        _atomic_write(rc_path, updated_rc)
    return InstallResult(selected_shell, rc_path, shell_path, config_path, changed)


def _manifest_rc_paths(root: Path, home: Path) -> list[Path]:
    manifest_path = root / "install.json"
    paths: list[Path] = []
    try:
        manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
        raw_path = manifest.get("rc_path")
        if isinstance(raw_path, str):
            candidate = Path(raw_path).expanduser().resolve()
            if candidate.parent == home:
                paths.append(candidate)
    except (OSError, ValueError, TypeError):
        pass
    for candidate in (home / ".zshrc", home / ".bashrc"):
        if candidate not in paths:
            paths.append(candidate)
    return paths


def uninstall(purge: bool = False, home: Path | None = None) -> UninstallResult:
    """Remove only compress-owned integration; preserve user data unless purging."""
    user_home = _home(home)
    location_home = user_home if home is not None else None
    root = config_dir(location_home)
    changed_paths: list[Path] = []
    for rc_path in _manifest_rc_paths(root, user_home):
        try:
            content = rc_path.read_text(encoding="utf-8")
        except FileNotFoundError:
            continue
        updated = _block_pattern().sub("", content, count=1)
        if updated != content:
            _atomic_write(rc_path, updated, stat.S_IMODE(rc_path.stat().st_mode))
            changed_paths.append(rc_path)

    (root / "shell.sh").unlink(missing_ok=True)
    (root / "install.json").unlink(missing_ok=True)
    if purge:
        if root.exists():
            shutil.rmtree(root)
        states = state_dir(location_home)
        if states.exists():
            shutil.rmtree(states)
    return UninstallResult(tuple(changed_paths), purge)
